### ISSUE TITLE
USER STORY: CREATE USER ACCOUNT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/litterpickers#2]
Epic: #1 

As a **site user** I can **create an account** so that **I can use the account to add content**.

### Acceptance Criteria: 

* A site user can create an account

### Tasks:

- [ ] Install allauth, update requirements.txt
- [ ] Add allauth to main urls.py file, add allauth to settings.py INSTALLED_APPS
- [ ] Add SITE ID = 1 and LOGIN(and LOGOUT_REDIRECT_URL = '/' (for home page)
- [ ] Add href="{% url 'account_signup' %} to navigation in base.html template
- [ ] Create new account at /accounts/signup
---
