### ISSUE TITLE
USER STORY: SITE ADMINISTRATION

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/litterpickers#6]
Epic: #5 

As a **manager of the site** I can **login to the admin panel** so that **I can manage the site**.

### Acceptance Criteria: 

* SuperUser is able to login to the admin panel and view models.

### Tasks:

- [x] Create SuperUser account
- [x] Login to admin panel
- [x] Add admin views
---
