### ISSUE TITLE
USER STORY: ADMIN PANEL WYSIWYG EDITOR

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/litterpickers#7]
Epic: #5

As an **site administrator** I can **use a WYSIWYG  editor** so that **I can easily add content**.

### Acceptance Criteria: 

* WYSIWYG Editor displays in Admin Panel

### Tasks:

- [x] Install Summernote (update requirements.txt)
- [x] Add Summernote to installed apps (settings.py)
- [x] Add path to urls.py
- [x] Add to admin.py
- [x] Migrate
---
